"""Simplified research tools that coordinate with built-in Claude tools.

This module provides minimal coordination tools while letting agents use
the built-in WebSearch and WebFetch capabilities directly.
"""

import json
import os

# Import from parent directory structure
import sys
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    print("Warning: python-dotenv not found. Using environment variables only.")

# Import logging when available
try:
    from .logging_config import get_logger
    _logger = get_logger("research_tools")
    _logger.debug("Research tools logging initialized")
except ImportError:
    _logger = None

try:
    from claude_agent_sdk import tool
except ImportError:
    # Fallback decorator for when the SDK is not available
    def tool(name, description, parameters):
        def decorator(func):
            return func
        return decorator
    print("Warning: claude_agent_sdk not found. Using fallback tool decorator.")


@tool("save_research_findings", "Save research findings to session storage", {
    "topic": str,
    "findings": str,
    "sources": str,
    "session_id": str
})
async def save_research_findings(args: dict[str, Any]) -> dict[str, Any]:
    """Save research findings by returning data for external file creation.

    NOTE: Work Product 1 (SERP metadata + scraped/cleaned results) is automatically
    created by the zplayground1 search tool's save_work_product function.
    This tool is for saving supplementary findings data."""
    if _logger:
        _logger.info(f"Preparing research findings for topic: {args.get('topic', 'Unknown')}")

    # Validate required arguments
    try:
        topic = args["topic"]
        findings = args["findings"]
        sources = args["sources"]
        session_id = args.get("session_id", str(uuid.uuid4()))
    except KeyError as e:
        error_msg = f"Missing required argument: {e}"
        return {"error": error_msg, "success": False}

    # Prepare research data structure
    research_data = {
        "topic": topic,
        "findings": findings,
        "sources": sources,
        "saved_at": datetime.now().isoformat(),
        "session_id": session_id
    }

    # Prepare file paths for external creation
    session_path = f"researchmaterials/sessions/{session_id}"
    findings_file = f"{session_path}/research_findings.json"

    kevin_dir = "/home/kjdragan/lrepos/claude-agent-sdk-python/KEVIN"
    timestamp = datetime.now().strftime('%H%M%S')
    kevin_findings_file = f"{kevin_dir}/research_findings_{session_id[:8]}_{timestamp}.json"

    if _logger:
        _logger.info(f"Research findings prepared for {topic} ({len(findings)} characters)")

    # Return data and file paths for external file creation
    return {
        "content": [{
            "type": "text",
            "text": f"Research findings for '{topic}' prepared for file creation. Session {session_id}, {len(findings)} characters of research content."
        }],
        "research_data": research_data,
        "session_file_path": findings_file,
        "kevin_file_path": kevin_findings_file,
        "session_id": session_id,
        "success": True
    }


@tool("create_research_report", "Create formatted report content and provide the filepath where it should be saved", {
    "topic": str,
    "content": str,
    "session_id": str,
    "format": str,
    "report_type": str  # e.g., "draft", "final", "editorial_review", "editorial_feedback"
})
async def create_research_report(args: dict[str, Any]) -> dict[str, Any]:
    """Create formatted report content and return it with the recommended filepath.

    NOTE: MCP tools cannot save files directly due to sandboxing. This tool formats the report
    and returns the content along with the recommended filepath. The agent MUST then use the
    Write tool to save the content to the recommended filepath.
    """
    if _logger:
        _logger.info(f"Creating research report for topic: {args.get('topic', 'Unknown')}")

    topic = args["topic"]
    content = args["content"]
    session_id = args.get("session_id", str(uuid.uuid4()))
    format_type = args.get("format", "markdown")
    report_type = args.get("report_type", "report")  # draft, final, editorial_review, etc.

    # Create formatted report content
    report_content = f"""# Research Report: {topic}

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Session ID:** {session_id}
**Report Type:** {report_type}

---

{content}

---

*This report was generated by the Multi-Agent Research System using Claude Agent SDK.*
"""

    # Determine the correct subdirectory based on report type
    if "editorial" in report_type.lower() or "review" in report_type.lower() or "feedback" in report_type.lower():
        subdir = "working"  # Editorial reviews and feedback go to working directory
    elif report_type.lower() == "final":
        subdir = "final"  # Final reports go to final directory
    else:
        subdir = "working"  # Drafts and other reports go to working directory

    # Generate filename with sanitized topic
    sanitized_topic = topic.replace(' ', '_').replace('/', '_')[:50]  # Limit length
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    extension = "md" if format_type == "markdown" else "txt"

    # Include report type in filename for clarity with numbered work product prefixes
    # Format: PREFIX-topic_timestamp.ext (where PREFIX is work product number + optional letter suffix)
    base_prefix_map = {
        "draft": "2",                   # Work Product 2: Initial Report
        "report": "2",                  # Work Product 2: Initial Report
        "revised": "2",                 # Work Product 2: Revised Report (will get suffix)
        "revision": "2",                # Work Product 2: Revised Report (will get suffix)
        "editorial_review": "3",        # Work Product 3: Editorial Review
        "editorial": "3",               # Work Product 3: Editorial Review
        "editorial_feedback": "3",      # Work Product 3: Editorial Review
        "final": "4",                   # Work Product 4: Final Summary
        "final_summary": "4",           # Work Product 4: Final Summary
        "research_findings": "1",       # Work Product 1: Research
        "search_verification": "1",     # Work Product 1: Research
        "research": "1"                 # Work Product 1: Research
    }
    base_prefix = base_prefix_map.get(report_type.lower(), "2")  # Default to 2- if unknown

    # Count existing files with this prefix to determine suffix (A, B, C, etc.)
    # Use absolute path based on KEVIN_WORKPRODUCTS_DIR or hardcoded path
    kevin_base = os.environ.get('KEVIN_WORKPRODUCTS_DIR', '/home/kjdragan/lrepos/claude-agent-sdk-python/KEVIN')
    session_dir = Path(kevin_base) / "sessions" / session_id / subdir
    session_dir.mkdir(parents=True, exist_ok=True)
    existing_files = list(session_dir.glob(f"{base_prefix}*-*.{extension}"))
    if not existing_files:
        # First file of this type - no suffix
        prefix = base_prefix
    else:
        # Calculate suffix based on count (A, B, C, D, etc.)
        suffix_letter = chr(65 + len(existing_files))  # 65 is ASCII for 'A'
        prefix = f"{base_prefix}{suffix_letter}"

    filename = f"{prefix}-{sanitized_topic}_{timestamp}.{extension}"
    # Use absolute path to ensure agents save files to correct location
    recommended_filepath = str(session_dir / filename)

    # For final reports, also provide work_products path
    work_products_filepath = None
    if report_type.lower() == "final":
        work_products_dir = Path(kevin_base) / "work_products" / "reports"
        work_products_dir.mkdir(parents=True, exist_ok=True)
        work_products_filepath = str(work_products_dir / filename)

    if _logger:
        _logger.info(f"Research report formatted for {topic} ({len(report_content)} characters)")

    # Return instructions for the agent to save the file
    instruction_text = f"""Report content created for '{topic}' ({len(report_content)} characters).

⚠️  CRITICAL: You MUST now save this report using the Write tool.

Use this EXACT filepath:
    {recommended_filepath}

The Write tool will automatically create any necessary directories."""

    # For final reports, also create an accessible copy in working directory as fallback
    if report_type.lower() == "final":
        working_dir = Path(kevin_base) / "sessions" / session_id / "working"
        working_dir.mkdir(parents=True, exist_ok=True)
        working_copy = str(working_dir / filename)
        instruction_text += f"""

IMPORTANT: Also save a FINAL copy in working directory as fallback:
    {working_copy}

This ensures the final report is accessible even if finalization fails."""

    if work_products_filepath:
        instruction_text += f"""

Also save a copy for easy access at:
    {work_products_filepath}"""

    return {
        "content": [{
            "type": "text",
            "text": instruction_text
        }],
        "report_content": report_content,
        "recommended_filepath": recommended_filepath,
        "work_products_filepath": work_products_filepath,
        "session_id": session_id,
        "report_size": len(report_content),
        "report_type": report_type,
        "success": True
    }


@tool("get_session_data", "Retrieve data from a research session", {
    "session_id": str,
    "data_type": str
})
async def get_session_data(args: dict[str, Any]) -> dict[str, Any]:
    """Retrieve data from a research session."""
    session_id = args["session_id"]
    data_type = args.get("data_type", "all")

    # Try KEVIN directory structure first (primary)
    kevin_base = os.environ.get('KEVIN_WORKPRODUCTS_DIR', '/home/kjdragan/lrepos/claude-agent-sdk-python/KEVIN')
    session_path = Path(f"{kevin_base}/sessions/{session_id}")

    # Fallback to legacy researchmaterials structure
    if not session_path.exists():
        session_path = Path(f"researchmaterials/sessions/{session_id}")

    if not session_path.exists():
        return {
            "content": [{
                "type": "text",
                "text": f"Session {session_id} not found in KEVIN or researchmaterials directories."
            }]
        }

    result_data = {}

    # Try to load research findings (new standardized format)
    if data_type in ["all", "findings", "research_findings", "research_content", "summary"]:
        # PRIORITY 1: Look for Work Product 1 (SERP metadata + scraped/cleaned content) in working/ directory
        working_dir = session_path / "working"
        if working_dir.exists():
            # Find Work Product 1 files (1-*.md or 1A-*.md, etc.)
            work_product_1_files = list(working_dir.glob("1*-*.md"))
            # Exclude report files (those with "report" in the name)
            work_product_1_files = [f for f in work_product_1_files if "report" not in f.name.lower()]

            if work_product_1_files:
                try:
                    # Get the most recent Work Product 1 file
                    latest_wp1 = max(work_product_1_files, key=os.path.getctime)
                    with open(latest_wp1, encoding='utf-8') as f:
                        wp1_content = f.read()
                        result_data["work_product_1"] = wp1_content
                        result_data["work_product_1_path"] = str(latest_wp1)
                        result_data["work_product_1_name"] = latest_wp1.name

                        # This is the primary research data that report_agent should use
                        if _logger:
                            _logger.info(f"✅ Found Work Product 1: {latest_wp1.name} ({len(wp1_content)} chars)")
                except Exception as e:
                    result_data["work_product_1_error"] = f"Error reading Work Product 1: {str(e)}"

        # PRIORITY 2: Look for research_findings.json (supplementary metadata)
        findings_file = session_path / "research_findings.json"
        if findings_file.exists():
            try:
                with open(findings_file, encoding='utf-8') as f:
                    findings_data = json.load(f)
                    result_data["findings"] = findings_data

                    # For backward compatibility, also provide structured data for report agents
                    if "sources" in findings_data and "findings" in findings_data:
                        # This is the new standardized format
                        result_data["standardized_research"] = {
                            "research_topic": findings_data.get("research_topic"),
                            "research_timestamp": findings_data.get("research_timestamp"),
                            "sources": findings_data.get("sources", []),
                            "findings": findings_data.get("findings", []),
                            "key_themes": findings_data.get("key_themes", []),
                            "content_summary": findings_data.get("content_summary", ""),
                            "search_metrics": findings_data.get("search_metrics", []),
                            "source_analysis": findings_data.get("source_analysis", {}),
                            "quality_assessment": findings_data.get("quality_assessment", {}),
                            "research_metadata": findings_data.get("research_metadata", {})
                        }
            except (json.JSONDecodeError, Exception) as e:
                # Handle corrupted research findings file
                result_data["findings_error"] = f"Error reading research findings: {str(e)}"

        # PRIORITY 3: Fallback to old research/ directory structure (legacy)
        if "work_product_1" not in result_data:
            research_dir = session_path / "research"
            if research_dir.exists():
                research_files = list(research_dir.glob("*.md"))
                if research_files:
                    result_data["fallback_research_files"] = [str(f) for f in research_files]
                    # Try to read the most recent research file
                    try:
                        latest_file = max(research_files, key=os.path.getctime)
                        with open(latest_file, encoding='utf-8') as f:
                            result_data["fallback_research_content"] = f.read()
                    except Exception as e:
                        result_data["fallback_error"] = f"Error reading fallback research file: {str(e)}"

    # Try to load research report
    if data_type in ["all", "report"]:
        report_files = list(session_path.glob("research_report.*"))
        if report_files:
            try:
                report_file = report_files[0]
                with open(report_file, encoding='utf-8') as f:
                    result_data["report"] = f.read()
            except Exception as e:
                result_data["report_error"] = f"Error reading research report: {str(e)}"
        else:
            # Fallback: look for any markdown files that might be reports in subdirectories
            for subdir in ["research", "working", "final"]:
                subdir_path = session_path / subdir
                if subdir_path.exists():
                    report_files = list(subdir_path.glob("*report*.md"))
                    if report_files:
                        try:
                            latest_report = max(report_files, key=os.path.getctime)
                            with open(latest_report, encoding='utf-8') as f:
                                result_data["fallback_report"] = f.read()
                                result_data["fallback_report_path"] = str(latest_report)
                                break
                        except Exception as e:
                            result_data["fallback_report_error"] = f"Error reading fallback report: {str(e)}"

    # Try to load session state
    if data_type in ["all", "state"]:
        state_file = session_path / "session_state.json"
        if state_file.exists():
            with open(state_file, encoding='utf-8') as f:
                result_data["state"] = json.load(f)

    # Create comprehensive status message
    status_items = []
    if "work_product_1" in result_data:
        status_items.append(f"Work Product 1 (SERP metadata + scraped content): {result_data['work_product_1_name']}")
    if "findings" in result_data:
        status_items.append("research findings")
    if "standardized_research" in result_data:
        status_items.append("structured research data")
    if "fallback_research_content" in result_data:
        status_items.append("fallback research content")
    if "report" in result_data:
        status_items.append("research report")
    if "fallback_report" in result_data:
        status_items.append("fallback report")
    if "state" in result_data:
        status_items.append("session state")

    # Add error messages if any
    error_messages = []
    if "work_product_1_error" in result_data:
        error_messages.append(result_data["work_product_1_error"])
    if "findings_error" in result_data:
        error_messages.append(result_data["findings_error"])
    if "report_error" in result_data:
        error_messages.append(result_data["report_error"])
    if "fallback_error" in result_data:
        error_messages.append(result_data["fallback_error"])

    if status_items:
        status_text = f"Successfully retrieved {', '.join(status_items)} for session {session_id}"
    else:
        status_text = f"No data found for session {session_id}"

    if error_messages:
        status_text += "\n\nWarnings:\n" + "\n".join(error_messages)

    # Add Work Product 1 instruction for report_agent
    if "work_product_1" in result_data:
        status_text += f"\n\n📊 PRIMARY RESEARCH DATA: Work Product 1 contains SERP search results with metadata (titles, URLs, snippets, relevance scores) followed by scraped and AI-cleaned content from each source. This is the complete raw research data for report generation."

    return {
        "content": [{
            "type": "text",
            "text": status_text
        }],
        "session_data": result_data,
        "data_availability": {
            "has_work_product_1": "work_product_1" in result_data,
            "has_research_findings": "findings" in result_data,
            "has_structured_research": "standardized_research" in result_data,
            "has_fallback_research": "fallback_research_content" in result_data,
            "has_report": "report" in result_data,
            "has_fallback_report": "fallback_report" in result_data,
            "has_session_state": "state" in result_data,
            "data_types_found": list(result_data.keys())
        }
    }
